/** @format */

export const ListUsers = {
  PENDING: "LIST_USERS_PENDING",
  SUCCESS: "LIST_USERS_SUCCESS",
  FAILED: "LIST_USERS_FAILED",
};

export const CreateUser = {
  PENDING: "CREATE_USER_PENDING",
  SUCCESS: "CREATE_USER_SUCCESS",
  FAILED: "CREATE_USER_FAILED",
};
